### ISSUE TITLE
extracting signatures and Plots

### ISSUE THREAD

**Issue by ernestopicardi** [flo-compbio/gopca#11]
Hi Florian,
I tried your tool on my dataset. It worked correctly generating the binary output file. Then I applied your accessory script gopca_extract_signature_matrix.py to get all signatures in textual format. However, I get the following error:
macbook-pro-15-di-ernesto-2:SLAnew ernesto$ gopca_extract_signature_matrix.py -g gopca.pickle -o out
Traceback (most recent call last):
  File "/usr/local/bin/gopca_extract_signature_matrix.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/gopca/cli/extract_signature_matrix.py", line 92, in main
    E = ExpMatrix(genes=sig_labels, samples=samples, X=result.S)
  File "/usr/local/lib/python2.7/site-packages/pandas/core/generic.py", line 2744, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'GOPCASignatureMatrix' object has no attribute 'S'

In addition, in the main paper you indicate Plot scripts gopca_plot_*.py but I'm unable to find them in the package.

Many thanks in advance,
Ernesto

**Comment by flo-compbio** [comment]
Hi Ernesto,

Sorry for the problems. To explain things a bit, I've reworked the internals of my program since the publication (e.g., switching from matplotlib to plotly for plotting), and focused on the development of the Python API, because that's what I'm using in my own research. I've neglected the command-line scripts in the process, which is why they weren't working anymore. I've just pushed a new version (0.2.3) that makes the following scripts work again:

- gopca_print_info.py
- gopca_extract_signatures.py
- gopca_extract_signatures_excel.py
- gopca_extract_signature_matrix.py
- gopca_plot_signature_matrix.py

You can install the latest version like this:

`pip install gopca==0.2.3`

Or only for your user like this:

`pip install --user gopca==0.2.3`

Documentation of the command-line arguments of each script is here:
http://gopca.readthedocs.io/en/latest/cli.html

I know there's still more work to be done, including providing additional scripts and improving the documentation. If you let me know what you need, I'm happy to provide more updates and add the functionalities you're missing.

Best, Florian

**Comment by ernestopicardi** [comment]
Hi Florian,
the new version works very well  as well as embedded scripts.
I have only a simple request (if possible). In my case, I have only two conditions with biological replicates and prefix equal to Ctrl_ and Als_. In the final plot, Ctrl_ and Als_ samples are not ordered. Please have a look at the attached pdf
[gopca.pdf](https://github.com/flo-compbio/gopca/files/830499/gopca.pdf)
. Is there a way to control the order of sample names? 
Many thanks in advance,
Ernesto
