### ISSUE TITLE
get_xlmhg_stat() takes at most 4 arguments (6 given)

### ISSUE THREAD

**Issue by hjistb** [flo-compbio/gopca#13]
Hi Florian,
  When I was running go-pca.py, I got the following errors:
---------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "go-pca.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/python27/lib/python2.7/site-packages/gopca/cli/go_pca.py", line 340, in main
    run = M.run()
  File "/usr/local/python27/lib/python2.7/site-packages/gopca/gopca.py", line 730, in run
    self.matrix, config.params, gse_analysis, W, d+1)
  File "/usr/local/python27/lib/python2.7/site-packages/gopca/gopca.py", line 513, in _generate_pc_signatures
    exact_pval='if_significant')
  File "/usr/local/python27/lib/python2.7/site-packages/genometools/enrichment/analysis.py", line 429, in get_rank_based_enrichment
    exact_pval=exact_pval, table=table)
  File "/usr/local/python27/lib/python2.7/site-packages/xlmhg/test.py", line 223, in get_xlmhg_test_result
    stat, cutoff = mhg_cython.get_xlmhg_stat(indices, N, K, X, L, tol)
TypeError: get_xlmhg_stat() takes at most 4 arguments (6 given)
---------------------------------------------------------------------------------------
I found in file "/usr/local/python27/lib/python2.7/site-packages/xlmhg/mhg.py", line 60, in get_xlmhg_stat, there were 4 arguments (v, X, L, tol=DEFAULT_TOL).

Do I miss something, or it is the internal error?

**Comment by YuanJIE-H** [comment]
Hello,have you solved this problem? I meet the same bug but i can not solve it

**Comment by hjistb** [comment]
Sorry. It's quite a long time ago. I've forgotten.
